### ISSUE TITLE
need Narrative reader

### ISSUE THREAD

**Issue by Coder5432** [ecksbee/goldlord-midas#17]
1. the narrative fact reader- allows user to read a narrative fact. this is a XBRL fact that can be pages long. (does not fit within grid)
2. footnote reader- for a given fact, there should be an indicator in the grid that indicates it is annotated. If selected, the user can read the footnotes for the reader. This should have similar functionality to the narrative fact reader. Footnotes can be very lengthy (page long+)

**Comment by Coder5432** [comment]
<s>3. additional work: (low priority) images within narrative text/footnotes should be rendered inline with the base64 encoding. This should be done server-side.</s>

**Comment by joshuanario** [comment]
inlining image issue is migrated to the telefacts repo https://github.com/ecksbee/telefacts/issues/57

#18  #19   close this issue
