### ISSUE TITLE
Browse button

### ISSUE THREAD

**Issue by joshuanario** [ecksbee/goldlord-midas#3]
![image](https://user-images.githubusercontent.com/16855011/146642326-245f0216-c385-47b2-9bab-c0a663a6054e.png)
Add a button in the selector page.

On clicking the button, the app will use the selected subject and relationship set to get the network hash that will be used to fetch the renderable.  Using the fetched renderable, the app should render the main panel.

![image](https://user-images.githubusercontent.com/16855011/146642774-e91374a1-d8a3-458d-9b23-f2921b1e9534.png)
The main panel must have three tabs: "Presentation", "Definition", and "Calculation".  On the first rendering of the main panel, it must render the `PGrid` of the renderables under the `Presentation` tab. (See `pGridViewer.js` and `transformPGrid.js`).  Rendering the `PGrid` should have a datagrid/spreadsheet look-and-feel.

![image](https://user-images.githubusercontent.com/16855011/146642945-b3abc88e-90f4-4971-96b3-93d71dc27f69.png)
The title bar of the main panel must be labelled with the `Title` of the selected relationship set and the `Name` of the entity.

**Comment by Coder5432** [comment]
How long is too long for the title? how about more than 50 characters.

**Comment by joshuanario** [comment]
> How long is too long for the title? how about more than 50 characters.

Just use css for that. 

```css
.truncate {
  width: 250px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

Source:  https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

**Comment by joshuanario** [comment]
Updated work item to included the title bar of the main panel.
